/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package repuestos.UI;

import repuestos.Logic.Controller;

/**
 *
 * @author Xelop
 */
public class AddPart extends javax.swing.JFrame {

    /**
     * Creates new form AddPart
     */
    Controller Control;
    public AddPart(Controller pControl) {
        initComponents();
    Control=pControl;
    Control.changeCurrentUI(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _btn_AddPart = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        _lbl_Name = new javax.swing.JLabel();
        _d = new javax.swing.JLabel();
        _txt_Name = new javax.swing.JTextField();
        _lbl_City = new javax.swing.JLabel();
        _txt_TradeMark = new javax.swing.JTextField();
        _txt_Percetage = new javax.swing.JTextField();
        _lbl_Identification = new javax.swing.JLabel();
        _txt_Factory = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        _btn_AddPart.setText("Done");
        _btn_AddPart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _btn_AddPartMouseClicked(evt);
            }
        });

        _lbl_Name.setText("Name");

        _d.setText("TradeMark");

        _txt_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _txt_NameActionPerformed(evt);
            }
        });

        _lbl_City.setText("Income Percentage");

        _txt_TradeMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _txt_TradeMarkActionPerformed(evt);
            }
        });

        _txt_Percetage.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                _txt_PercetageAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        _txt_Percetage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _txt_PercetageActionPerformed(evt);
            }
        });
        _txt_Percetage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                _txt_PercetageKeyReleased(evt);
            }
        });

        _lbl_Identification.setText("Factory Id");

        _txt_Factory.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                _txt_FactoryKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(_lbl_Name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_txt_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(_d)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_txt_TradeMark, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_lbl_City)
                            .addComponent(_lbl_Identification))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_txt_Percetage, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_txt_Factory, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_lbl_Name)
                    .addComponent(_txt_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_d)
                    .addComponent(_txt_TradeMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_lbl_City)
                    .addComponent(_txt_Percetage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_lbl_Identification)
                    .addComponent(_txt_Factory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(_btn_AddPart)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(_btn_AddPart))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _txt_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__txt_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__txt_NameActionPerformed

    private void _txt_TradeMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__txt_TradeMarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__txt_TradeMarkActionPerformed

    private void _txt_PercetageAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event__txt_PercetageAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event__txt_PercetageAncestorAdded

    private void _txt_PercetageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__txt_PercetageActionPerformed
        //TODO add your handling code here:

    }//GEN-LAST:event__txt_PercetageActionPerformed

    private void _btn_AddPartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__btn_AddPartMouseClicked
        // TODO add your handling code here:
        Control.addPart(_txt_Percetage.getText(), _txt_Name.getText(), _txt_TradeMark.getText(), _txt_Factory.getText());
    }//GEN-LAST:event__btn_AddPartMouseClicked

    private void _txt_PercetageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__txt_PercetageKeyReleased
        // TODO add your handling code here:
        if(Character.isDigit(evt.getKeyChar())||evt.getExtendedKeyCode()==8) {
        } else
            _txt_Percetage.setText(""+_txt_Percetage.getText().substring(0, _txt_Percetage.getText().length() - 1));
        
    }//GEN-LAST:event__txt_PercetageKeyReleased

    private void _txt_FactoryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__txt_FactoryKeyReleased
        // TODO add your handling code here:
        if(Character.isDigit(evt.getKeyChar())||evt.getExtendedKeyCode()==8) {
        } else
            _txt_Factory.setText(""+_txt_Factory.getText().substring(0, _txt_Factory.getText().length() - 1));
        
    }//GEN-LAST:event__txt_FactoryKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AddPart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _btn_AddPart;
    private javax.swing.JLabel _d;
    private javax.swing.JLabel _lbl_City;
    private javax.swing.JLabel _lbl_Identification;
    private javax.swing.JLabel _lbl_Name;
    private javax.swing.JTextField _txt_Factory;
    private javax.swing.JTextField _txt_Name;
    private javax.swing.JTextField _txt_Percetage;
    private javax.swing.JTextField _txt_TradeMark;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
