/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package repuestos.UI;

import java.util.ArrayList;
import javax.swing.JTextArea;

/**
 *
 * @author Xelop
 */
public class AddTelephone extends javax.swing.JFrame {

    /**
     * Creates new form AddTelephone
     */
    JTextArea TelephoneDisplay;
    ArrayList<String> Telephones;
    public AddTelephone(JTextArea pDisplay, ArrayList<String> pNumbers) {
        initComponents();
        TelephoneDisplay=pDisplay;
        Telephones=pNumbers;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _lbl_Telephone = new javax.swing.JLabel();
        _txt_Number = new javax.swing.JTextField();
        _btn_AddTelephone = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        _lbl_Telephone.setText("Telephone: ");

        _txt_Number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                _txt_NumberKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                _txt_NumberKeyReleased(evt);
            }
        });

        _btn_AddTelephone.setText("Add");
        _btn_AddTelephone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _btn_AddTelephoneMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(_lbl_Telephone)
                        .addGap(18, 18, 18)
                        .addComponent(_txt_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 41, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(_btn_AddTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_lbl_Telephone)
                    .addComponent(_txt_Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(_btn_AddTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _btn_AddTelephoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__btn_AddTelephoneMouseClicked
        // TODO add your handling code here:
        Telephones.add(_txt_Number.getText());
        TelephoneDisplay.setText(TelephoneDisplay.getText()+ _txt_Number.getText()+"\n");
        this.dispose();
        
    }//GEN-LAST:event__btn_AddTelephoneMouseClicked

    private void _txt_NumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__txt_NumberKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event__txt_NumberKeyPressed

    private void _txt_NumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__txt_NumberKeyReleased
        // TODO add your handling code here:
        if(Character.isDigit(evt.getKeyChar())||evt.getExtendedKeyCode()==8) {
        } else
            _txt_Number.setText(""+_txt_Number.getText().substring(0, _txt_Number.getText().length() - 1));
        
    }//GEN-LAST:event__txt_NumberKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTelephone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTelephone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTelephone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTelephone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AddTelephone().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _btn_AddTelephone;
    private javax.swing.JLabel _lbl_Telephone;
    private javax.swing.JTextField _txt_Number;
    // End of variables declaration//GEN-END:variables
}
