/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package repuestos.UI;

import java.util.ArrayList;
import repuestos.Logic.Controller;

/**
 *
 * @author Xelop
 */
public class ListPartswithCars extends javax.swing.JFrame {

    /**
     * Creates new form ListPartswithCars
     */
    Controller Control;
    ArrayList<String> ListValues;
    public ListPartswithCars(Controller pControl) {
        initComponents();
        Control=pControl;
    }
    
    public void setCars(){
        for(int counter=0; counter<ListValues.size(); counter++){
            _txa_RelationCarsParts.setText(_txa_RelationCarsParts.getText()+"\n"+ ListValues.get(counter));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        _txt_Model = new javax.swing.JTextField();
        _lbl_Year = new javax.swing.JLabel();
        _txt_Year = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        _txa_RelationCarsParts = new javax.swing.JTextArea();
        _btn_List = new javax.swing.JButton();
        _btn_Done = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Model");

        _txt_Model.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                _txt_ModelKeyReleased(evt);
            }
        });

        _lbl_Year.setText("Year");

        _txt_Year.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                _txt_YearKeyReleased(evt);
            }
        });

        _txa_RelationCarsParts.setColumns(20);
        _txa_RelationCarsParts.setRows(5);
        jScrollPane1.setViewportView(_txa_RelationCarsParts);

        _btn_List.setText("List");
        _btn_List.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _btn_ListMouseClicked(evt);
            }
        });
        _btn_List.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btn_ListActionPerformed(evt);
            }
        });

        _btn_Done.setText("Done");
        _btn_Done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btn_DoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(_lbl_Year))
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(_txt_Year, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(_txt_Model, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(_btn_List)))
                        .addContainerGap(73, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_btn_Done)
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(_txt_Model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_btn_List))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_lbl_Year)
                    .addComponent(_txt_Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_btn_Done)
                        .addGap(41, 41, 41))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _btn_ListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__btn_ListMouseClicked
        // TODO add your handling code here:
        Control.listPartsbyCar(_txt_Model.getText(), _txt_Year.getText());
    }//GEN-LAST:event__btn_ListMouseClicked

    private void _btn_DoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btn_DoneActionPerformed
        // TODO add your handling code here:
        new MainInterface(Control).setVisible(true);
        this.dispose();
    }//GEN-LAST:event__btn_DoneActionPerformed

    private void _btn_ListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btn_ListActionPerformed
        // TODO add your handling code here:
        ListValues= Control.listPartsbyCar(_txt_Model.getText(), _txt_Year.getText());
        setCars();
    }//GEN-LAST:event__btn_ListActionPerformed

    private void _txt_ModelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__txt_ModelKeyReleased
        // TODO add your handling code here:
        if(Character.isDigit(evt.getKeyChar())||evt.getExtendedKeyCode()==8) {
        } else{
            _txt_Model.setText(""+_txt_Model.getText().substring(0, _txt_Model.getText().length() - 1));
        }
    }//GEN-LAST:event__txt_ModelKeyReleased

    private void _txt_YearKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__txt_YearKeyReleased
        // TODO add your handling code here:
        if(Character.isDigit(evt.getKeyChar())||evt.getExtendedKeyCode()==8) {
        } else{
            _txt_Year.setText(""+_txt_Year.getText().substring(0, _txt_Year.getText().length() - 1));
        }
    }//GEN-LAST:event__txt_YearKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListPartswithCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListPartswithCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListPartswithCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListPartswithCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ListPartswithCars().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _btn_Done;
    private javax.swing.JButton _btn_List;
    private javax.swing.JLabel _lbl_Year;
    private javax.swing.JTextArea _txa_RelationCarsParts;
    private javax.swing.JTextField _txt_Model;
    private javax.swing.JTextField _txt_Year;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
