/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package repuestos.UI;

import java.net.InterfaceAddress;
import javax.swing.JFrame;
import repuestos.Logic.Controller;

/**
 *
 * @author Xelop
 */
public class MainInterface extends javax.swing.JFrame {

    /**
     * Creates new form MainInterface
     */
    Controller Control;
    public MainInterface(Controller pControl) {
        initComponents();
        Control=pControl;
        Control.changeCurrentUI(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _lbl_MainTitle = new javax.swing.JLabel();
        _btn_AddClient = new javax.swing.JButton();
        _btn_ModifyClient = new javax.swing.JButton();
        _btn_ListClients = new javax.swing.JButton();
        _btn_SuspendClient = new javax.swing.JButton();
        _btn_AddPart = new javax.swing.JButton();
        _btn_ErasePart = new javax.swing.JButton();
        _btn_ErasePart1 = new javax.swing.JButton();
        _btn_ErasePart2 = new javax.swing.JButton();
        _btn_ModifyPartPrice = new javax.swing.JButton();
        _btn_ListParts = new javax.swing.JButton();
        _btn_ProviderParts = new javax.swing.JButton();
        _btn_CreateOrder = new javax.swing.JButton();
        _btn_OrderItems = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        _lbl_MainTitle.setText("Car Replacement Parts Shop");

        _btn_AddClient.setText("Add Client");
        _btn_AddClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _btn_AddClientMouseClicked(evt);
            }
        });
        _btn_AddClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btn_AddClientActionPerformed(evt);
            }
        });

        _btn_ModifyClient.setText("Modify Client");
        _btn_ModifyClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _btn_ModifyClientMouseClicked(evt);
            }
        });
        _btn_ModifyClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btn_ModifyClientActionPerformed(evt);
            }
        });

        _btn_ListClients.setText("List Clients");
        _btn_ListClients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _btn_ListClientsMouseClicked(evt);
            }
        });
        _btn_ListClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btn_ListClientsActionPerformed(evt);
            }
        });

        _btn_SuspendClient.setText("Suspend Clients");
        _btn_SuspendClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _btn_SuspendClientMouseClicked(evt);
            }
        });

        _btn_AddPart.setText("Add Part");
        _btn_AddPart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _btn_AddPartMouseClicked(evt);
            }
        });
        _btn_AddPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btn_AddPartActionPerformed(evt);
            }
        });

        _btn_ErasePart.setText("Erase Part");
        _btn_ErasePart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _btn_ErasePartMouseClicked(evt);
            }
        });

        _btn_ErasePart1.setText("Associate Part/Provider");
        _btn_ErasePart1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _btn_ErasePart1MouseClicked(evt);
            }
        });

        _btn_ErasePart2.setText("Associate Part/Cars");
        _btn_ErasePart2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _btn_ErasePart2MouseClicked(evt);
            }
        });

        _btn_ModifyPartPrice.setText("Modify Part's Price");
        _btn_ModifyPartPrice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _btn_ModifyPartPriceMouseClicked(evt);
            }
        });

        _btn_ListParts.setText("List Parts Per Vehicule");
        _btn_ListParts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btn_ListPartsActionPerformed(evt);
            }
        });

        _btn_ProviderParts.setText("Provider's Parts");
        _btn_ProviderParts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _btn_ProviderPartsMouseClicked(evt);
            }
        });

        _btn_CreateOrder.setText("Make Order");
        _btn_CreateOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _btn_CreateOrderMouseClicked(evt);
            }
        });

        _btn_OrderItems.setText("Order Items");
        _btn_OrderItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btn_OrderItemsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(_lbl_MainTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(_btn_AddClient)
                                    .addComponent(_btn_ModifyClient))
                                .addGap(118, 118, 118)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(_btn_AddPart)
                                    .addComponent(_btn_ErasePart)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(_btn_SuspendClient)
                                .addGap(80, 80, 80)
                                .addComponent(_btn_ErasePart1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(189, 189, 189)
                                .addComponent(_btn_ErasePart2))
                            .addComponent(_btn_ListClients))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_btn_ProviderParts)
                            .addComponent(_btn_ListParts)
                            .addComponent(_btn_ModifyPartPrice)
                            .addComponent(_btn_CreateOrder)
                            .addComponent(_btn_OrderItems))))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_lbl_MainTitle)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_btn_AddClient)
                    .addComponent(_btn_AddPart)
                    .addComponent(_btn_ModifyPartPrice))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_btn_ModifyClient)
                    .addComponent(_btn_ErasePart)
                    .addComponent(_btn_ListParts))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(_btn_ProviderParts)
                        .addGap(34, 34, 34)
                        .addComponent(_btn_CreateOrder)
                        .addGap(33, 33, 33)
                        .addComponent(_btn_OrderItems))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_btn_SuspendClient)
                            .addComponent(_btn_ErasePart1))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_btn_ListClients)
                            .addComponent(_btn_ErasePart2))))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _btn_AddClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__btn_AddClientMouseClicked
        new InsertClient(Control).setVisible(true);
        this.dispose();
    }//GEN-LAST:event__btn_AddClientMouseClicked

    private void _btn_ModifyClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__btn_ModifyClientMouseClicked
        // TODO add your handling code here:
        new FindClient(Control,1).setVisible(true);
    }//GEN-LAST:event__btn_ModifyClientMouseClicked

    private void _btn_ModifyClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btn_ModifyClientActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event__btn_ModifyClientActionPerformed

    private void _btn_ListClientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__btn_ListClientsMouseClicked
        // TODO add your handling code here:
        new ListClients(Control).setVisible(true);
        
    }//GEN-LAST:event__btn_ListClientsMouseClicked

    private void _btn_ListClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btn_ListClientsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__btn_ListClientsActionPerformed

    private void _btn_SuspendClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__btn_SuspendClientMouseClicked
        // TODO add your handling code here:
        new FindClient(Control, 2).setVisible(true);
        this.dispose();
    }//GEN-LAST:event__btn_SuspendClientMouseClicked

    private void _btn_AddPartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__btn_AddPartMouseClicked
        // TODO add your handling code here:
        new AddPart(Control).setVisible(true);
        this.dispose();
    }//GEN-LAST:event__btn_AddPartMouseClicked

    private void _btn_ErasePartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__btn_ErasePartMouseClicked
        // TODO add your handling code here:
        new FindPart(Control,1).setVisible(true);
        this.dispose();
    }//GEN-LAST:event__btn_ErasePartMouseClicked

    private void _btn_ErasePart1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__btn_ErasePart1MouseClicked
        // TODO add your handling code here:
        new FindPart(Control, 2).setVisible(true);
        this.dispose();
    }//GEN-LAST:event__btn_ErasePart1MouseClicked

    private void _btn_ErasePart2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__btn_ErasePart2MouseClicked
        // TODO add your handling code here:
        new FindPart(Control, 3).setVisible(true);
        this.dispose();
    }//GEN-LAST:event__btn_ErasePart2MouseClicked

    private void _btn_ModifyPartPriceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__btn_ModifyPartPriceMouseClicked
        // TODO add your handling code here:
        new FindPart(Control,5).setVisible(true);
        this.dispose();
    }//GEN-LAST:event__btn_ModifyPartPriceMouseClicked

    private void _btn_ProviderPartsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__btn_ProviderPartsMouseClicked
        // TODO add your handling code here:
        new FindPart(Control,4).setVisible(true);
        this.dispose();
    }//GEN-LAST:event__btn_ProviderPartsMouseClicked

    private void _btn_CreateOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__btn_CreateOrderMouseClicked
        // TODO add your handling code here:
        new FindClient(Control, 3).setVisible(true);
        this.dispose();
    }//GEN-LAST:event__btn_CreateOrderMouseClicked

    private void _btn_AddPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btn_AddPartActionPerformed
        // TODO add your handling code here:
        new AddPart(Control).setVisible(true);
        this.dispose();
    }//GEN-LAST:event__btn_AddPartActionPerformed

    private void _btn_ListPartsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btn_ListPartsActionPerformed
        // TODO add your handling code here:
        new ListPartswithCars(Control).setVisible(true);
        this.dispose();
    }//GEN-LAST:event__btn_ListPartsActionPerformed

    private void _btn_OrderItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btn_OrderItemsActionPerformed
        // TODO add your handling code here:
        new OrderItems(Control).setVisible(true);
        this.dispose();
    }//GEN-LAST:event__btn_OrderItemsActionPerformed

    private void _btn_AddClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btn_AddClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__btn_AddClientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainInterface(Controller.getInstance()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _btn_AddClient;
    private javax.swing.JButton _btn_AddPart;
    private javax.swing.JButton _btn_CreateOrder;
    private javax.swing.JButton _btn_ErasePart;
    private javax.swing.JButton _btn_ErasePart1;
    private javax.swing.JButton _btn_ErasePart2;
    private javax.swing.JButton _btn_ListClients;
    private javax.swing.JButton _btn_ListParts;
    private javax.swing.JButton _btn_ModifyClient;
    private javax.swing.JButton _btn_ModifyPartPrice;
    private javax.swing.JButton _btn_OrderItems;
    private javax.swing.JButton _btn_ProviderParts;
    private javax.swing.JButton _btn_SuspendClient;
    private javax.swing.JLabel _lbl_MainTitle;
    // End of variables declaration//GEN-END:variables
}
